const media = {
  phone: require('../assets/icon/phone.png'),
  lock: require('../assets/icon/lock.png'),
  facebook: require('../assets/icon/facebook.png'),
  zalo: require('../assets/icon/zalo.png'),
  google: require('../assets/icon/google.png'),
  add: require('../assets/icon/add.png'),
  checked: require('../assets/icon/checked.png'),
  unchecked: require('../assets/icon/unchecked.png'),
  user: require('../assets/icon/user.png'),
  location: require('../assets/icon/location.png'),
  calendar: require('../assets/icon/calendar.png'),
  radio_unchecked: require('../assets/icon/radio_unchecked.png'),
  radio_checked: require('../assets/icon/radio_checked.png'),
  chevron_arrow_down: require('../assets/icon/chevron_arrow_down.png'),
  chevron_arrow_up: require('../assets/icon/chevron_arrow_up.png'),
  store: require('../assets/icon/store.png'),
  clock: require('../assets/icon/clock.png'),
  pickup_click: require('./icon/product.png'),
  pickup: require('./icon/product_inactive.png'),
  order:require('./icon/list_inactive.png'),
  order_click:require('./icon/list.png'),
  statistics:require('./icon/statistic_inactive.png'),
  statistics_click:require('./icon/statistic.png'),
  notification:require('./icon/notify_inactive.png'),
  notification_click:require('./icon/notify.png'),
  account: require('./icon/user_bottom_tab_inactive.png'),
  account_click:require('./icon/user_bottom_tab.png'),
  drawer:require('./icon/drawer.png'),
  repair:require('./icon/repair.png'),
  rate:require('./icon/airbnb-star.png'),
  star:require('./icon/star_filled.png'),
  star_With_Border:require('./icon/star_corner.png'),
  delete: require('../assets/icon/delete.png'),

  header_background: require('../assets/img/header_background.png'),
  provision: require('../assets/img/provision.png'),
  imageProduct1:require('./img/imageProduc1.png'),
  imageProduct2:require('./img/imageProduc2.png'),
  image:require('./img/image.png'),
  avatar_default: require('../assets/img/user.png'),
  notify_check_all: require('../assets/icon/notify_check_all.png'),
  chervron_left:require('./icon/Chevron_left.png'),
  avata:require('./icon/Account.png'),
  next:require('./icon/next.png'),
  setting:require('./icon/settings.png'),
  logout:require('./icon/logout.png'),
  support:require('./icon/support.png'),
  bank:require('./icon/bank.png'),


};

export default media;
